name: Automated tests

on:
  pull_request:
    branches:
      - staging
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: npm install, test
        run: |
          npm install
          npm run astro check
